# Generated by Django 5.2.1 on 2025-08-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("view_users_list", "Может просматривать список пользователей")
                ],
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователь",
            },
        ),
    ]
