# Generated by Django 5.2.1 on 2025-08-07 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(verbose_name="Тема сообщения")),
                ("body", models.TextField(verbose_name="Тело сообщения")),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщении",
                "db_table": "message",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Email получателя рассылки",
                    ),
                ),
                ("full_name", models.CharField(verbose_name="ФИО получателя рассылки")),
                (
                    "comment",
                    models.TextField(
                        verbose_name="Комментарий к профилю получатель рассылки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
                "db_table": "recipient",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_send",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время первой отправки"
                    ),
                ),
                (
                    "last_send",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время окончания отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("running", "Запущена"),
                            ("completed", "Завершена"),
                        ],
                        default="created",
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mailing.message",
                        verbose_name="FK. Сообщение рассылки",
                    ),
                ),
                (
                    "recipient",
                    models.ManyToManyField(
                        to="mailing.recipient",
                        verbose_name="ManyToMany. Получатель рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "db_table": "broadcast",
                "ordering": ["id"],
            },
        ),
    ]
