# Generated by Django 5.2.1 on 2025-08-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mailing.message",
                verbose_name="Сообщение рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="recipient",
            field=models.ManyToManyField(
                to="mailing.recipient", verbose_name="Получатель/получатели рассылки"
            ),
        ),
        migrations.CreateModel(
            name="BroadcastAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_date_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время попытки рассылки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[(True, "Успешно"), (False, "Не успешно")],
                        verbose_name="Статус попытки",
                    ),
                ),
                ("response", models.TextField(verbose_name="Ответ почтового сервера")),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="mailing.broadcast",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылки",
                "db_table": "broadcast_attempt",
                "ordering": ["id"],
            },
        ),
    ]
