# Generated by Django 5.2.1 on 2025-08-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_broadcast_message_alter_broadcast_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="last_send",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время окончания отправки"
            ),
        ),
        migrations.AlterField(
            model_name="broadcastattempt",
            name="status",
            field=models.CharField(
                choices=[("success", "Успешно"), ("fail", "Не успешно")],
                verbose_name="Статус попытки",
            ),
        ),
    ]
