# Generated by Django 5.2.1 on 2025-08-10 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_broadcast_last_send_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing.message",
                verbose_name="Сообщение рассылки",
            ),
        ),
        migrations.AlterField(
            model_name="broadcastattempt",
            name="broadcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing.broadcast",
                verbose_name="Рассылка",
            ),
        ),
    ]
