# Generated by Django 5.2.1 on 2025-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_broadcast_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="comment",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Комментарий к профилю получатель рассылки",
            ),
        ),
    ]
