# Generated by Django 5.2.1 on 2025-08-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_recipient_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcast",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("can_view_all_broadcasts", "Может просматривать все рассылки")
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщении",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("can_view_all_recipients", "Может просматривать всех клиентов")
                ],
                "verbose_name": "Получатель рассылки",
                "verbose_name_plural": "Получатели рассылки",
            },
        ),
    ]
