# Generated by Django 5.2.1 on 2025-08-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_broadcast_options_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="broadcast",
            options={
                "ordering": ["id"],
                "permissions": [
                    ("can_view_all_broadcasts", "Может просматривать все рассылки"),
                    ("broadcast_shutdown", "Отключение рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
